version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lesson1Stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1puhw2su7hvaf"
s3_prefix = "lesson1Stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=736266384336.dkr.ecr.us-east-1.amazonaws.com/mycloudformationf8d10587/helloworldfunction19d43fc4repo"]
